#!/usr/bin/env bash

# TODO migrate to https://www.gnu.org/software/stow/manual/stow.html?

### Symlinks to backup places
ln -ST "$HOME/Pictures" "$HOME/Syncthing/0Phone/Pictures"

### Symlinks to this repo
DIR="$(readlink -f "$(dirname "$0")")" || exit

# Cloud
ln -sTv ~/.config/rclone/rclone.conf $SYNC/.config/rclone.conf 2>/dev/null

# NixOS
sudo ln -sTv $DIR/nixos /etc/nixos 2>/dev/null

# Home
# NOTE: don't add ~/.config/transmission/settings.json to this list, it has ever changing entries
paths=(
  ~/.bash_profile # to prevent tmux from running ~/.profile
  ~/.bashrc
  ~/.blerc
  ~/.config/alacritty
  ~/.config/eww
  ~/.config/flameshot
  ~/.config/i3status-rust
  ~/.config/kitty
  ~/.config/lf
  ~/.config/mako
  ~/.config/mimeapps.list
  ~/.config/mpv
  ~/.config/nnn/config
  ~/.config/nnn/plugins
  ~/.config/nsxiv
  ~/.config/nvim
  ~/.config/rofi
  ~/.config/scripts
  ~/.config/starship.toml
  ~/.config/syncthing-1/config.xml
  ~/.config/syncthing-2/config.xml
  ~/.config/syncthingtray.ini
  ~/.config/vimiv
  ~/.config/waybar
  ~/.config/zsh
  ~/.editorconfig
  ~/.fuzzy-home-ignore
  ~/.gitconfig
  ~/.ignore # for ripgrep
  ~/.lesskey
  ~/.local/share/applications
  ~/.local/share/lf/marks
  ~/.npmrc
  ~/.profile
  ~/.tmux.conf
  ~/.zprofile
)

printf "%s\n" "${paths[@]}" | while read -r path; do
  path_bac="${path/~/$DIR/home}"
  if [[ ! -e "$path_bac" ]]; then
    if [[ ! -e "$path" ]]; then
      echo "$path"
      echo "No config to backup: $path"
      exit 1
    else
      mkdir -p "$(dirname "$path_bac")"
      echo "Backing up $path to $(readlink -f "$path_bac")"
      mv "$path" "$path_bac"
    fi
  fi
  ln -sTv "$path_bac" "$path" 2>/dev/null
done
