#!/usr/bin/env bash

if [[ -e "$VIMIV_TAGFILE" ]]; then
  cat "$VIMIV_TAGFILE" 2>/dev/null | tail +3 | xargs -d '\n' -I{} mv -vf "{}" . &&
    wc1="$(tail +3 <"$VIMIV_TAGFILE")" &&
    trash "$VIMIV_TAGFILE" || rm -vf "$VIMIV_TAGFILE" ||
    true
fi

if [[ -e "$SXIV_SEL" ]]; then
  cat "$SXIV_SEL" 2>/dev/null | xargs -d '\n' -I{} mv -vf "{}" . &&
    wc2="$(wc -l <"$SXIV_SEL")" &&
    trash "$SXIV_SEL" || rm -vf "$SXIV_SEL" ||
    true
fi

notify-send "Moved $((wc1 + wc2)) images"
