#!/usr/bin/env bash

socket=/tmp/mpv-socket

if pgrep mpv >/dev/null; then
  echo "loadfile '$*' replace" | socat - "$socket"
  echo '{ "command": ["set_property", "pause", false] }' | socat - "$socket"
else
  mpv --osd-fractions --keep-open --input-ipc-server="$socket" "$@"
fi
