#!/usr/bin/env bash

if [ "$(stat -c %d "$1")" = "$(stat -c %d "$(dirname "$2")")" ]; then
  $TERMINAL -e bash -c 'mv -f -- "$@" || read' '' "${@:3}" &
else
  $TERMINAL -e sh -c 'rsync -ah --progress --remove-source-files "$@" || read' '' "${@:3}" &
fi
