#!/usr/bin/env bash

# swaymsg [app_id=".*"] kill
# swaymsg [class=".*"] kill
# sync
# sleep 2

# 3. Sync filesystems (ensures Brave's save is actually on disk)

# 4. Use the "kexec" or "reboot" force flags if systemctl hangs

swaymsg exit
sudo systemctl poweroff
