#!/usr/bin/env bash

# INFO: # To avoid `restore session` popups in chromium based browsers.
swaymsg '[app_id=.*]kill' # INFO: browser should be targeted specifically, ie `pkill -u $USER` won't help
sleep 1
sudo poweroff
