#!/usr/bin/env bash

swaymsg [app_id=".*"] kill
swaymsg [class=".*"] kill

sleep 1

# 3. Sync filesystems (ensures Brave's save is actually on disk)
sync

# 4. Use the "kexec" or "reboot" force flags if systemctl hangs
sudo systemctl poweroff --force --force
