#!/usr/bin/env bash

charge_stop=$(cat '/sys/class/power_supply/BAT0/charge_control_end_threshold')

charge_points=(50 80 100)

if [[ "$*" -lt 0 ]]; then
  change_direction=-1
else
  change_direction=1
fi

for charge_point_i in $(seq 0 $((${#charge_points[@]} - 1))); do
  if [ ! "$charge_stop" -gt "${charge_points[*]:$charge_point_i:1}" ]; then
    charge_point_cur=$charge_point_i
    break
  fi
done

charge_point_new=$((charge_point_cur + change_direction))
case $charge_point_new in
-1)
  charge_point_new=0
  ;;
"${#charge_points[@]}")
  charge_point_new=$((charge_point_new - 1))
  ;;
esac

charge_stop_new=${charge_points[$charge_point_new]}

sudo tlp setcharge $((charge_stop_new - 5)) "$charge_stop_new"
