#!/usr/bin/env bash

files=$(find "$(dirname "$@")" -maxdepth 1 -type f | sort)
# if [[ $(wc -l <<<"$files") -gt 100 ]]; then
nsxiv -n"$( (grep -nF -m1 "$(basename "$@")" | cut -d: -f1) <<<"$files")" - <<<"$files"
# else
#   vimiv "$@"
# fi
