#!/usr/bin/env bash

files=$(find "$(dirname "$@")" -type f -maxdepth 1 | sort)
# if [[ $(wc -l <<<"$files") -gt 100 ]]; then
sxiv -n"$( (grep -n -m1 "$(basename "$@")" | cut -d: -f1) <<<"$files")" - <<<"$files"
# else
#   vimiv "$@"
# fi
