#!/usr/bin/env bash

in="$1"
out="$("$SCRIPTS/bac" "$1")"
shift
seg_counter=1
concat_path=/tmp/segments.txt
rm "$concat_path"
echo "$@" >"$out.txt"
while (("$#" >= 2)); do
  seg_path="/tmp/part${seg_counter}.mp4"
  rm "$seg_path"
  if [[ "$1" == '-' ]]; then
    ffmpeg -to "$2" -i "$in" -c copy "$seg_path"
  elif [[ "$2" == '-' ]]; then
    ffmpeg -ss "$1" -i "$in" -c copy "$seg_path"
  else
    ffmpeg -ss "$1" -to "$2" -i "$in" -c copy "$seg_path"
  fi
  echo "file '$seg_path'" >>$concat_path
  ((seg_counter += 1))
  shift 2
done

ffmpeg -f concat \
  -safe 0 \
  -fflags +genpts \
  -i $concat_path \
  -c copy "$out"

notify-send "Saved concatenated video under $out"
