#!/usr/bin/env bash

set -e

if [[ -z "$*" ]]; then
  tag='1'
else
  tag="$*"
fi

tagfile="/home/nix/.local/share/vimiv/tags/$tag"

cat "$tagfile" | tail +3 | xargs -d '\n' -I{} mv -vf "{}" .

trash "$tagfile" || rm -vf "$tagfile"
