#!/usr/bin/env bash
# hyprctl activewindow -j | jq

hyprctl workspaces -j | jq -c "{active_ws: \"\", wss:sort_by(.id) | map(.name)}"
socat -u "UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - \
  | while read -r line; do 
  ws_name="$(sed -nr 's/^workspace>>(.*)$/\1/p' <<<"$line")"
  if [[ -n "$ws_name" ]]; then 
    hyprctl workspaces -j | jq -c "{active_ws: \"$ws_name\", wss:sort_by(.id) | map(.name)}"
  fi
done 
