#!/bin/sh

script_name=$(basename "$0")

file='/sys/class/backlight/intel_backlight/brightness'
mult_inv=$(calc '1/4')
max_abs=$(calc "$(brightnessctl m)")
min_abs=2
min_rel=$(calc "($min_abs/$max_abs)^$mult_inv") 
# to smooth out change at low value

brightness ()
{
  echo $(calc "floor((($(brightnessctl g)/$max_abs)^$mult_inv-$min_rel)/(1-$min_rel)*100)")
}

echo "$(brightness)"

inotifywait -mqe modify "$file" | while read -r _; do
  brightness="$(brightness)"
  notify-send -a "$script_name" -c 'desktop' "$brightness"
  echo "$brightness"
done
