#!/usr/bin/env bash

bat_path="/sys/class/power_supply/BAT0"

bat_read() {
  status=$(cat "$bat_path/status")
  capacity=$(cat "$bat_path/capacity")
  charge_stop=$(cat "$bat_path/charge_control_end_threshold")
}

print() {
  echo "{\"status\":\"$status\",\"capacity\":$capacity,\"charge_stop\":$charge_stop}"
}

bat_read
print

while true; do
  echo waiting
  inotifywait -qe CLOSE "$bat_path/model_name" -e CLOSE_WRITE "$bat_path/charge_control_end_threshold" >/dev/null
  bat_read
  print
  if [[ "$status" == "Not charging" && $capacity -lt $((charge_stop - 4)) ]]; then
    while true; do
      echo sleeping
      sleep 0.5
      bat_read
      if [[ "$status" == "Charging" || ! $capacity -lt $((charge_stop - 4)) ]]; then
        print
        break
      fi
    done
  elif [[ "$status" == "Charging" && $((charge_stop - 4)) -lt $capacity ]]; then
    while true; do
      sleep 0.5
      bat_read
      if [[ "$status" == "Not charging" || ! $((charge_stop - 4)) -lt $capacity ]]; then
        print
        break
      fi
    done
  fi
done

