#!/usr/bin/env bash

# hyprctl activewindow -j | jq

hyprctl activewindow -j | jq -r .title
socat -u "UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - \
  | while read -r line; do 
  title="$(sed -nr 's/^(activewindowtitlev2|activewindow)>>.*,(.*)$/\2/p' <<<"$line")"
  if [[ -n "$title" ]]; then 
    echo "$title"
  fi
done 
