#!/usr/bin/env bash

udiskie --smart-tray | while read -r line; do 
mount_dir="$(sed -nr 's/mounted .* on (.*)/\0/p' <<< "$line")"
if [[ -d "$mount_dir" ]]; then
  alacritty -e bash -c "nnn \"$mount_dir\"; bash"
fi
done
