#!/usr/bin/env bash

bat_path="/sys/class/power_supply/BAT0"
model_path="$bat_path/model_name"
status_path="$bat_path/status"
capacity_path="$bat_path/capacity"
charge_stop_path="$bat_path/charge_control_end_threshold"

bat_read() {
  status=$(cat "$status_path")
  capacity=$(cat "$capacity_path")
  charge_stop=$(cat "$charge_stop_path")
}

print() {
  echo "{\"status\":\"$status\",\"capacity\":$capacity,\"charge_stop\":$charge_stop}"
}

bat_read
print

while true; do
  inotifywait -qe CLOSE "$model_path" >/dev/null
  bat_read
  while [[ "$status" == "Not charging" && $charge_stop -gt $capacity ]]; do
    sleep 0.2
    bat_read
  done
  while [[ "$status" == "Charging" && $charge_stop -lt $capacity ]]; do
    sleep 0.2
    bat_read
  done
  print
done

