#!/bin/sh

app_name=$(basename "$0")
path='/sys/class/backlight/intel_backlight/brightness'
max=$(calc "$(brightnessctl m)^0.25")

brightness ()
{
  echo $(calc "floor(($(cat "$path")^0.25 * 100 / $max - 18)*100/82)") # accounting for brightnessctl exponent
}

echo "$(brightness)"

inotifywait -mqe modify "$path" | while read -r _; do
  brightness="$(brightness)"
  notify-send -a "$app_name" "$brightness"
  echo "$brightness"
done
