#!/usr/bin/env bash
### [nnn](https://github.com/jarun/nnn)
export NNN_TMPFILE=/tmp/.nnn.lastd
export NNN_SCOPE=1
export NNN_USE_EDITOR=1
export NNN_TRASH=1
export NNN_OPTS='rHRAJxE'
export NNN_ORDER="t:$HOME/Syncthing/Phone;t:$HOME/.local/share/Trash;t:$HOME/Downloads;t:/tmp;t:$SCREENSHOTS;t:/var/log"
export NNN_FIFO=/tmp/.nnn.fifo
export NNN_SEL='/tmp/.nnn.sel'
# [plugins](https://github.com/jarun/nnn/tree/master/plugins#nnn-plugins)
export NNN_PLUG;NNN_PLUG=$(tr -d '\n' <<<"
m:mtpmount;
d:diffs;
e:preview-tabbed;
;:preview-tui;
r:rsynccp;
R:renamer;
v:!mvg \$(cat /home/nix/.local/share/vimiv/tags/a | tail +3) . && rm /home/nix/.local/share/vimiv/tags/a*;
>:!mogrify -rotate 90 \"\$PWD/\$nnn\"*;
<:!mogrify -rotate -90 \"\$PWD/\$nnn\"*;
s:!echo -n>$NNN_SEL*;
n:!nautilus . &*;
y:!printf '%q' \"\$PWD/\$nnn\" | sed 's|^$HOME|~|' | wl-copy*;
Y:!printf '%q' \"\$PWD\" | sed 's|^$HOME|~|' | wl-copy*;
v:!\$($SCRIPTS/vimiv-tag-paste) && rm /home/nix/.local/share/vimiv/tags/a*;
p:!printf '0c%s' \"\$(wl-paste | sed 's|^~|$HOME|')\" >\$NNN_PIPE*;
a:!file=\$($SCRIPTS/fuzzy-home) && echo -n \"0c\$file\" >\$NNN_PIPE*;
f:!file=\$($SCRIPTS/fuzzy) && echo -n \"0c\$file\" >\$NNN_PIPE*;
F:!file=\$($SCRIPTS/fuzzy-ignored) && echo -n \"0c\$file\" >\$NNN_PIPE*;
")
export NNN_BMS;NNN_BMS=$(tr -d '\n' <<<"
d:$HOME/Downloads;
m:/run/media/$USER;
b:$SYNC;
S:$SCREENSHOTS;
t:/tmp;
T:$HOME/.local/share/Trash/files;
s:$HOME/Syncthing;
w:$HOME/WS;
w:$WIKI;
")
