#!/usr/bin/env bash

export NNN_COMM='nnn -Tr;. /tmp/.nnn.lastd' # Tr isn't handled by NNN_OPTS

### [nnn](https://github.com/jarun/nnn)
export NNN_TMPFILE=/tmp/.nnn.lastd
export NNN_SCOPE=1
export NNN_USE_EDITOR=1
export NNN_TRASH=1
export NNN_OPTS='rHRAJxE'
export NNN_ORDER="t:$HOME/Syncthing/Phone;t:$HOME/.local/share/Trash/files;t:$HOME/.local/share/Trash/info;t:$HOME/Downloads;t:/tmp;"
export NNN_FIFO=/tmp/.nnn.fifo
export NNN_SEL='/tmp/.nnn.sel'
# [plugins](https://github.com/jarun/nnn/tree/master/plugins#nnn-plugins)
export NNN_PLUG;NNN_PLUG=$(tr -d '\n' <<<"
d:diffs;
e:preview-tabbed;
m:mtpmount;
;:preview-tui;
R:renamer;
r:rsynccp;
a:!file=\$($SCRIPTS/fuzzy-home) && echo -n \"0c\$file\" >\$NNN_PIPE*;
f:!file=\$($SCRIPTS/fuzzy) && echo -n \"0c\$file\" >\$NNN_PIPE*;
F:!file=\$($SCRIPTS/fuzzy-ignored) && echo -n \"0c\$file\" >\$NNN_PIPE*;
<:!mogrify -rotate -90 \"\$PWD/\$nnn\"*;
>:!mogrify -rotate 90 \"\$PWD/\$nnn\"*;
n:!nautilus . &*;
p:!printf '0c%s' \"\$(wl-paste | sed 's|^~|$HOME|')\" >\$NNN_PIPE*;
s:!echo -n>$NNN_SEL*;
v:!$SCRIPTS/vimiv-tag-paste*;
y:!printf '%q' \"\$PWD/\$nnn\" | sed 's|^$HOME|~|' | wl-copy*;
Y:!printf '%q' \"\$PWD\" | sed 's|^$HOME|~|' | wl-copy*;
")
export NNN_BMS;NNN_BMS=$(tr -d '\n' <<<"
d:$HOME/Downloads;
D:$SYNC;
m:/run/media/$USER;
s:$HOME/Syncthing;
S:$SCREENSHOTS;
T:$HOME/.local/share/Trash/files;
t:/tmp;
w:$HOME/WS;
W:$WIKI;
")
