"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "fl0wsnake"
email = "lastthursdayist@gmail.com"

[ui]
pager = "delta"
diff-formatter = ":git"

[aliases]
l = ["log", "-r", "@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()"] # Compact log of your own changes relative to trunk
la = ["log", "-r", "all()"] # Full log of everything
cl = ["log", "-r", "trunk()..@-", "--reversed", "-T", "description ++ '\n---\n\n'", "--no-graph", "--no-pager"] # Copy commit descriptions for PR — useful for paste into GitHub
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"] # Move nearest bookmark up to @- (must also add revset-alias below)
pba = ["git", "push", "--all"] # Push all bookmarks
rbt = ["rebase", "-d", "trunk()"] # Rebase all your changes on top of trunk

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
