#!/usr/bin/env bash

imgs=$(cat)

case "$@" in
'h' | 'C-h') printf '%s' "$imgs" | xargs -0 -P 8 -n 4 mogrify -auto-orient -rotate -90 ;;
'l' | 'C-l') printf '%s' "$imgs" | xargs -0 -P 8 -n 4 mogrify -auto-orient -rotate 90 ;;
'j' | 'C-j' | 'k' | 'C-k') printf '%s' "$imgs" | xargs -0 -P 8 -n 4 mogrify -auto-orient -rotate 180 ;;
'Return' | 'C-Return')
  kill "$("$SCRIPTS_SWAY"/focused-window-pid)"
  nsxiv -t "$(dirname "$imgs")"
  ;;
'q' | 'C-q') xargs -I{} trash "{}" <<<"$imgs" && notify-send "Trashed $(wc -l <<<"$imgs") images" ;;
'w' | 'C-w') echo "$imgs" | xargs -d'\n' readlink -e >"$SXIV_SEL" && notify-send "Selected $(wc -l <<<"$imgs") images" ;;
'r' | 'C-r') $TERMINAL -e sh -c "vidir - <<<\"$imgs\"" ;;
'y' | 'C-y') wl-copy -t "$(xdg-mime query filetype "$imgs")" <"$imgs" && notify-send "Image clipped" ;;
'p' | 'C-p') wl-copy <<<"$imgs" && notify-send "Image path clipped" ;;
'e' | 'C-e') gimp -sdf "$imgs" & ;;
'd' | 'C-d') printf '%s' "$imgs" | xargs -0 -P 8 -n 4 ripdrag -a & ;;
esac
