#!/usr/bin/env bash
pid_w=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.type=="con") | select(.focused==true).pid')
cwd=$(
  ps --no-headers -e -o pid,ppid,comm \
    | awk -v p="$pid_w" '$2==p&&$3!="kitten"{p=$1;print}' \
    | sed -nr "s@\s*([0-9]+).*($SHELL_COMM|$EDITOR|$EXPLORER).*\$@\1@p" \
    | tail -1    \
    | xargs -I{} readlink -e /proc/{}/cwd
)
if [ -d "$cwd" ]; then
  echo "$cwd"
else
  echo "$HOME"
fi
