#!/usr/bin/env bash

app_name=$(basename "$0")

layouts="$(swaymsg -t get_inputs | jq '.[] | select(.identifier=="1:1:AT_Translated_Set_2_keyboard").xkb_layout_names')"

echo "$(swaymsg -t get_inputs | jq -r 'limit(1; .[] | select(has("xkb_active_layout_name"))).xkb_active_layout_name')"

swaymsg -t subscribe -m '["input"]' \
  | jq --unbuffered -r '.input.xkb_active_layout_name' \
  | while IFS=$'\n' read -r layout; do
  if [ ! "$layout" == 'null' ]; then
    echo "$layout"
    notify-send -a "$app_name" '' "$(echo "$layouts" | jq -r ". | map(if (. == \"$layout\") then \"<span bgcolor='white' color='black'>\"+.+\"</span>\" else . end) | join(\"\n\")")"
  fi
done 
