#!/usr/bin/env bash

app_name=$(basename "$0")

shorten() {
  if [[ "$*" == "Ukrainian" ]]; then
    echo "UA"
  elif [[ "$*" == "English (US)" ]]; then
    echo "EN"
  else
    echo "$@"
  fi
}

echo "$(shorten "$(swaymsg -t get_inputs | jq -r 'limit(1; .[] | select(has("xkb_active_layout_name"))).xkb_active_layout_name')")"

swaymsg -t subscribe -m '["input"]' \
  | jq --unbuffered -r '.input.xkb_active_layout_name' \
  | while IFS=$'\n' read -r layout; do
  echo "$(shorten "$layout")"
  notify-send -a "$app_name" "$layout"
done 
