#!/usr/bin/env bash

active_ws=''
wss="$(swaymsg -t get_workspaces -r | jq -c 'sort_by(.name|split(":")[0]) | map(.name|split(":")[1])')"

swaymsg -t subscribe '["workspace"]' -m | while read -r ws; do
if jq -e 'select(.change=="focus" or .change=="rename")'>/dev/null<<<"$ws"; then
  active_ws="$(jq -r '.current.name|split(":")[1]'<<<"$ws")"
  wss="$(swaymsg -t get_workspaces -r | jq -c 'sort_by(.name|split(":")[0]) | map(.name|split(":")[1])')"
  echo "{\"active_ws\":\"$active_ws\",\"wss\":$wss}"
fi
done
