#!/usr/bin/env bash

get_workspaces() {
  swaymsg -t get_workspaces -r | jq -c 'sort_by(.name|split(":")[0]) | map({"name":.name|split(":")[1], urgent:.urgent})'
}

current_ws=$(swaymsg -t get_tree | jq -r '.nodes[]|select(.active).current_workspace|split(":")[1]')
wss="$(get_workspaces)"

echo "{\"current_ws\":\"$current_ws\",\"wss\":$wss}"

swaymsg -mt subscribe '["workspace"]' | while read -r ws; do
change=$(jq -r '.change' <<<"$ws")
if [[ $change == "focus" || $change == "rename" ]]; then
  current_ws="$(jq -r '.current.name|split(":")[1]'<<<"$ws")"
  wss="$(get_workspaces)"
  echo "{\"current_ws\":\"$current_ws\",\"wss\":$wss}"
elif [[ $change == "init" || $change == "urgent" ]]; then
  wss="$(get_workspaces)"
  echo "{\"current_ws\":\"$current_ws\",\"wss\":$wss}"
fi
done
