#!/usr/bin/env bash

get_workspaces() {
  swaymsg -t get_workspaces -r | jq -c 'sort_by(.name|split(":")[0]) | map(.name|split(":")[1])'
}

active_ws=''
wss="$(get_workspaces)"

echo "$wss"

swaymsg -mt subscribe '["workspace"]' | while read -r ws; do
if jq -e 'select(.change=="focus" or .change=="rename")'>/dev/null<<<"$ws"; then
  active_ws="$(jq -r '.current.name|split(":")[1]'<<<"$ws")"
  wss="$(get_workspaces)"
  echo "{\"active_ws\":\"$active_ws\",\"wss\":$wss}"
elif jq -e 'select(.change=="init")'>/dev/null<<<"$ws"; then
  wss="$(get_workspaces)"
  echo "{\"active_ws\":\"$active_ws\",\"wss\":$wss}"
fi
done
