#!/usr/bin/env bash

pid_w=$(swaymsg -t get_tree | jq '.. | select(.type?) | select(.type=="con") | select(.focused==true).pid')
cwd=$(
  ps --no-headers -e -o pid,ppid,comm \
    | awk -v p="$pid_w" '$2==p{p=$1;print}' \
    | sed -nr "s@\s*([0-9]+).*($SHELL_COMM|$EDITOR|$EXPLORER)\$@\1@p" \
    | tail -1    \
    | xargs -I{} readlink -e /proc/{}/cwd
)
if [ -d "$cwd" ]; then
  echo "$cwd"
else
  echo "$HOME"
fi

# # Select the longest of all paths from the current process tree
# longest_pcwd=$(hyprctl activewindow -j \
#   | jq '.pid' \
#   | xargs pstree -p \
#   | sed -nE 's/ *\S* 0*([0-9]+).*/\1/p' \
#   | xargs -I{} readlink -e /proc/{}/cwd \
#   | awk '{if(length($0)>max){max=length($0);line=$0}}END{print line}')
#
# if [ -d "$longest_pcwd" ]; then
#   echo "$longest_pcwd"
# else
#   echo "$HOME"
# fi
#
